// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example usage:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt1hZLbwjLRvzeHXg2rGUH9Kd0jYngmiI',
    appId: '1:1074225461961:web:7d3f6105c0dac70e8d2b18',
    messagingSenderId: '1074225461961',
    projectId: 'nutify-81b2a',
    authDomain: 'nutify-81b2a.firebaseapp.com',
    storageBucket: 'nutify-81b2a.firebasestorage.app',
    measurementId: 'G-3HJ05B7H2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW-NgcXbSvdYXiuDLa_-oZZdJHhIjPaao',
    appId: '1:1074225461961:android:1200a880c6e978188d2b18',
    messagingSenderId: '1074225461961',
    projectId: 'nutify-81b2a',
    storageBucket: 'nutify-81b2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdefseJvuO27Vm647OfJixtsU3ybMJdMM',
    appId: '1:1074225461961:ios:a58e58b2bec7c7288d2b18',
    messagingSenderId: '1074225461961',
    projectId: 'nutify-81b2a',
    storageBucket: 'nutify-81b2a.firebasestorage.app',
    iosBundleId: 'com.example.nutify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdefseJvuO27Vm647OfJixtsU3ybMJdMM',
    appId: '1:1074225461961:ios:a58e58b2bec7c7288d2b18',
    messagingSenderId: '1074225461961',
    projectId: 'nutify-81b2a',
    storageBucket: 'nutify-81b2a.firebasestorage.app',
    iosBundleId: 'com.example.nutify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt1hZLbwjLRvzeHXg2rGUH9Kd0jYngmiI',
    appId: '1:1074225461961:web:fdfd77d31f22cd0a8d2b18',
    messagingSenderId: '1074225461961',
    projectId: 'nutify-81b2a',
    authDomain: 'nutify-81b2a.firebaseapp.com',
    storageBucket: 'nutify-81b2a.firebasestorage.app',
    measurementId: 'G-WTKSVQ3EZW',
  );
}
